# Generated by Django 4.2.17 on 2025-01-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
